'use client';
import {useRef,useState} from 'react';
import {Button} from '@/components/ui/Button';
import {createClient} from '@/lib/supabase/client';
import {createIexBatchQueue,iexBatchCounts,importIexBatch,validateIexBatch,type IexBatchItem,type IexBatchPreview} from './iexDamBatch';

export function IexDamBatchImporter(){
  const [queue,setQueue]=useState<IexBatchItem[]>([]),[source,setSource]=useState(''),[dateFormat,setDateFormat]=useState<'AUTO'|'DD/MM/YYYY'|'DD-MM-YYYY'>('AUTO');
  const [publishedAt,setPublishedAt]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
  const [progress,setProgress]=useState({current:'',completed:0});const cancelRequested=useRef(false);const counts=iexBatchCounts(queue);
  async function token(){const {data:{session}}=await createClient().auth.getSession();if(!session?.access_token)throw new Error('AUTHENTICATED_SESSION_REQUIRED');return session.access_token;}
  async function request(file:File,action:'preview'|'commit',preview?:IexBatchPreview){const body=new FormData();body.set('file',file);body.set('action',action);body.set('source_reference',source);body.set('official_source_confirmed',String(confirmed));body.set('date_format',dateFormat);
    if(preview)body.set('preview_checksum_sha256',preview.checksum_sha256);if(publishedAt)body.set('published_at',new Date(publishedAt).toISOString());
    const response=await fetch('/api/admin/market-prices',{method:'POST',body,headers:{Authorization:`Bearer ${await token()}`}});const result=await response.json();
    if(!response.ok)throw new Error(`${result.error||`HTTP_${response.status}`}${result.details?`: ${result.details}`:''}`);return result;}
  async function validateAll(){if(!confirmed||!source)return;setBusy(true);setError(null);cancelRequested.current=false;try{const result=await validateIexBatch(queue,async file=>(await request(file,'preview')).preview,()=>cancelRequested.current,items=>{setQueue(items);const active=items.find(item=>item.status==='VALIDATING');setProgress({current:active?.filename||'',completed:items.filter(item=>item.status==='VALIDATED'||item.status==='FAILED_VALIDATION').length});});setQueue(result);}catch(failure){setError(failure instanceof Error?failure.message:String(failure));}finally{setBusy(false);}}
  async function importValid(){if(!confirmed||!source)return;setBusy(true);setError(null);cancelRequested.current=false;try{const result=await importIexBatch(queue,async(file,preview)=>{await request(file,'commit',preview)},()=>cancelRequested.current,items=>{setQueue(items);const active=items.find(item=>item.status==='IMPORTING');setProgress({current:active?.preview?.delivery_dates?.[0]||active?.filename||'',completed:items.filter(item=>item.status==='IMPORTED'||item.status==='ALREADY_IMPORTED'||item.status==='FAILED_IMPORT').length});});setQueue(result);}catch(failure){setError(failure instanceof Error?failure.message:String(failure));}finally{setBusy(false);}}
  return <div className="space-y-3 text-xs" data-testid="iex-dam-batch-importer">
    <input data-testid="iex-dam-file" type="file" multiple accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={event=>{try{setQueue(createIexBatchQueue(Array.from(event.target.files||[])));setError(null);}catch(failure){setQueue([]);setError(failure instanceof Error?failure.message:String(failure));}}} className="block w-full text-slate-300"/>
    <input data-testid="iex-source-reference" value={source} onChange={event=>setSource(event.target.value)} placeholder="Official IEX export URL" className="w-full rounded border border-slate-700 bg-slate-950 px-3 py-2 text-slate-200"/>
    <div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><label className="text-slate-400">Export date format<select value={dateFormat} onChange={event=>setDateFormat(event.target.value as typeof dateFormat)} className="mt-1 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2 text-slate-200"><option value="AUTO">Auto (official DD-MM-YYYY)</option><option value="DD/MM/YYYY">DD/MM/YYYY</option><option value="DD-MM-YYYY">DD-MM-YYYY</option></select></label><label className="text-slate-400">Exchange published at (if shown)<input type="datetime-local" value={publishedAt} onChange={event=>setPublishedAt(event.target.value)} className="mt-1 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2 text-slate-200"/></label></div>
    <label className="flex gap-2 text-slate-300"><input data-testid="iex-official-confirmation" type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>I confirm the selected files are unmodified official IEX Day-Ahead Market exports and the official source reference applies to this batch.</label>
    {error&&<div role="alert" className="rounded border border-rose-800 p-2 text-rose-300">{error}</div>}
    {queue.length>0&&<section className="rounded border border-slate-700 p-3"><strong>BATCH IEX DAM IMPORT</strong><div>Selected files: {queue.length}</div><div className="mt-2 overflow-x-auto"><table className="w-full text-left"><thead><tr><th>File</th><th>Date</th><th>Blocks</th><th>MCP min / max / average</th><th>SHA-256</th><th>Provenance / verification</th><th>Status / error</th></tr></thead><tbody>{queue.map(item=><tr key={item.id} className="border-t border-slate-800"><td>{item.filename}</td><td>{item.preview?.delivery_dates?.join(', ')||'—'}</td><td>{item.preview?`${item.preview.received_blocks}/${item.preview.expected_blocks}`:'—'}</td><td>{item.preview?.mcp?`${item.preview.mcp.mcp_min_rs_per_mwh} / ${item.preview.mcp.mcp_max_rs_per_mwh} / ${item.preview.mcp.mcp_average_rs_per_mwh.toFixed(2)}`:'—'}</td><td className="font-mono text-[10px]">{item.preview?.checksum_sha256||'—'}</td><td>{item.preview?`OFFICIAL_SOURCE_CONFIRMED · ${item.preview.verification_status}`:'—'}</td><td>{item.status}{item.error?` · ${item.error}`:''}</td></tr>)}</tbody></table></div></section>}
    {busy&&<div data-testid="iex-batch-progress">{Math.min(progress.completed+1,queue.length)} / {queue.length} · {progress.current}</div>}
    <div className="flex gap-2"><Button data-testid="iex-preview-submit" disabled={!queue.length||!source||!confirmed||busy} onClick={validateAll} size="sm">{busy?'Processing…':'VALIDATE ALL'}</Button><Button data-testid="iex-import-submit" disabled={!queue.some(item=>item.status==='VALIDATED')||!confirmed||busy} onClick={importValid} size="sm">CONFIRM & IMPORT VALID FILES</Button>{busy&&<Button data-testid="iex-batch-cancel" onClick={()=>{cancelRequested.current=true}} size="sm" variant="outline">CANCEL ANALYSIS</Button>}</div>
    {queue.length>0&&<div data-testid="iex-batch-summary">Selected {counts.selected} · Validated {counts.validated} · Imported {counts.imported} · Already imported {counts.already_imported} · Failed {counts.failed}</div>}
  </div>;
}
