'use client';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import { Card, CardDescription, CardHeader, CardTitle } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';

const blank = { nameplate_energy_capacity_kwh:'',max_charge_power_kw:'',max_discharge_power_kw:'',minimum_soc_percent:'',maximum_soc_percent:'',initial_soc_percent:'',
  final_soc_requirement:'',final_soc_percent:'',charge_efficiency_percent:'',discharge_efficiency_percent:'',maximum_daily_throughput_kwh:'',
  degradation_cost_rs_per_kwh_throughput:'',available_blocks:'' };

export function BessProfileForm({ siteId }: { siteId: string }) {
  const [form,setForm]=useState(blank); const [status,setStatus]=useState('BESS_PROFILE_REQUIRED'); const [saving,setSaving]=useState(false);
  const supabase=useMemo(()=>createClient(),[]);
  const bearer=async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error('AUTHENTICATED_SESSION_REQUIRED');return{Authorization:`Bearer ${session.access_token}`};};
  useEffect(()=>{let active=true;void(async()=>{try{const response=await fetch(`/api/bess/profile?site_id=${encodeURIComponent(siteId)}`,{headers:await bearer()});const body=await response.json();if(!response.ok)throw new Error(body.error);if(!active)return;if(!body.profile){setForm(blank);setStatus(body.suppression_reason);return;}const p=body.profile;setForm(Object.fromEntries(Object.keys(blank).map((key)=>[key,key==='available_blocks'?(p[key]||[]).join(','):p[key]===null?'':String(p[key])])) as typeof blank);setStatus('Configured and auditable');}catch(error){if(active)setStatus(error instanceof Error?error.message:String(error));}})();return()=>{active=false;};},[siteId]); // eslint-disable-line react-hooks/exhaustive-deps
  const save=async(event:FormEvent)=>{event.preventDefault();setSaving(true);try{const numeric=['nameplate_energy_capacity_kwh','max_charge_power_kw','max_discharge_power_kw','minimum_soc_percent','maximum_soc_percent','initial_soc_percent','charge_efficiency_percent','discharge_efficiency_percent','maximum_daily_throughput_kwh','degradation_cost_rs_per_kwh_throughput'] as const;if(numeric.some((key)=>form[key].trim()==='')||!form.final_soc_requirement)throw new Error('ALL_EXPLICIT_BATTERY_PARAMETERS_REQUIRED');const profile={...Object.fromEntries(numeric.map((key)=>[key,Number(form[key])])),final_soc_requirement:form.final_soc_requirement,final_soc_percent:form.final_soc_percent.trim()?Number(form.final_soc_percent):null,available_blocks:form.available_blocks.trim()?form.available_blocks.split(',').map(Number):null};const response=await fetch('/api/bess/profile',{method:'PATCH',headers:{'Content-Type':'application/json',...(await bearer())},body:JSON.stringify({site_id:siteId,profile})});const body=await response.json();if(!response.ok)throw new Error(body.error);setStatus('Configured and auditable. Simulations use only these explicit parameters.');}catch(error){setStatus(error instanceof Error?error.message:String(error));}finally{setSaving(false);}};
  const fields:Array<[keyof typeof blank,string,string]>=[['nameplate_energy_capacity_kwh','Nameplate capacity','kWh'],['max_charge_power_kw','Maximum charge power','kW'],['max_discharge_power_kw','Maximum discharge power','kW'],['minimum_soc_percent','Minimum SOC','%'],['maximum_soc_percent','Maximum SOC','%'],['initial_soc_percent','Initial SOC','%'],['charge_efficiency_percent','Charge efficiency','%'],['discharge_efficiency_percent','Discharge efficiency','%'],['maximum_daily_throughput_kwh','Maximum daily throughput','kWh'],['degradation_cost_rs_per_kwh_throughput','Degradation cost','₹/kWh throughput'],['final_soc_percent','Minimum final SOC (policy-dependent)','%']];
  return <Card data-testid="bess-profile-form"><CardHeader><div><CardTitle>BESS Simulation Profile</CardTitle><CardDescription>Explicit site-scoped battery limits. No battery capability is inferred from sanctioned demand or load.</CardDescription></div></CardHeader><form onSubmit={save} className="space-y-4 p-6 pt-0"><div className="grid gap-3 md:grid-cols-3">{fields.map(([key,label,unit])=><label key={key} className="text-xs text-slate-300">{label} ({unit})<input type="number" min="0" step="any" value={form[key]} onChange={(e)=>setForm({...form,[key]:e.target.value})} className="mt-1 w-full rounded border border-slate-700 bg-slate-950 p-2"/></label>)}</div><label className="block text-xs text-slate-300">Final SOC requirement<select value={form.final_soc_requirement} onChange={(e)=>setForm({...form,final_soc_requirement:e.target.value})} className="mt-1 w-full rounded border border-slate-700 bg-slate-950 p-2"><option value="">Select explicitly</option><option value="RETURN_TO_INITIAL_SOC">Return to initial SOC</option><option value="MINIMUM_FINAL_SOC">Minimum final SOC</option></select></label><label className="block text-xs text-slate-300">Available blocks (optional comma-separated 1–96)<input value={form.available_blocks} onChange={(e)=>setForm({...form,available_blocks:e.target.value})} className="mt-1 w-full rounded border border-slate-700 bg-slate-950 p-2"/></label><div className="text-xs text-amber-200">{status}</div><div className="flex justify-end"><Button type="submit" size="sm" disabled={saving}>{saving?'Saving…':'Save BESS Profile'}</Button></div></form></Card>;
}
