'use client';
import { useMemo, useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import { BessSimulationPanel } from '@/features/bess/BessSimulationPanel';
import { BESS_SIZING_LABEL, BESS_SIZING_WARNING, candidateName, sizingCandidate, sizingHeatmap } from '@/lib/analytics/bess-sizing-presentation';
import type { BESSSizingCandidateContract, BESSSizingResponseContract } from '@/types/analytics-contracts';

const defaultCapacities=[500,1000,1500,2000,3000,4000];
const defaultPowers=[250,500,750,1000];
const money=(value:number)=>`₹${value.toLocaleString(undefined,{maximumFractionDigits:2})}`;
const parseCandidates=(value:string)=>value.split(',').map(item=>Number(item.trim())).filter(Number.isFinite);

export function HistoricalBessSizingPanel({siteId}:{siteId:string}) {
  const [inputDate,setInputDate]=useState('');
  const [capacityInput,setCapacityInput]=useState(defaultCapacities.join(', '));
  const [powerInput,setPowerInput]=useState(defaultPowers.join(', '));
  const [result,setResult]=useState<BESSSizingResponseContract|null>(null);
  const [selected,setSelected]=useState<BESSSizingCandidateContract|null>(null);
  const [loading,setLoading]=useState(false);const [error,setError]=useState<string|null>(null);
  const supabase=useMemo(()=>createClient(),[]);
  const cells=result?sizingHeatmap(result):[];
  const displayedCapacities=result?[...new Set(result.candidates.map(item=>item.capacity_kwh))].sort((a,b)=>a-b):defaultCapacities;
  const displayedPowers=result?[...new Set(result.candidates.map(item=>item.power_kw))].sort((a,b)=>a-b):defaultPowers;
  async function run(){setLoading(true);setError(null);setResult(null);setSelected(null);try{
    const capacityCandidates=parseCandidates(capacityInput);const powerCandidates=parseCandidates(powerInput);
    if(!capacityCandidates.length||!powerCandidates.length||capacityCandidates.some(value=>value<=0)||powerCandidates.some(value=>value<=0)||new Set(capacityCandidates).size!==capacityCandidates.length||new Set(powerCandidates).size!==powerCandidates.length||capacityCandidates.length*powerCandidates.length>30)throw new Error('INVALID_SIZING_CANDIDATE_GRID');
    const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error('AUTHENTICATED_SESSION_REQUIRED');
    const response=await fetch('/api/bess/sizing',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},
      body:JSON.stringify({site_id:siteId,input_date:inputDate,capacity_candidates_kwh:capacityCandidates,power_candidates_kw:powerCandidates})});
    const body=await response.json();if(!response.ok)throw new Error(body.error||`HTTP ${response.status}`);
    setResult(body.result);setSelected(sizingCandidate(body.result,body.result.best_candidate.capacity_kwh,body.result.best_candidate.power_kw));
  }catch(failure){setError(failure instanceof Error?failure.message:String(failure));}finally{setLoading(false);}}
  return <section className="space-y-4 rounded border border-purple-800 p-4" data-testid="historical-bess-sizing">
    <header><h2 className="font-bold text-purple-200">{BESS_SIZING_LABEL}</h2><strong className="text-xs text-amber-200">{BESS_SIZING_WARNING}</strong>
      <p className="text-xs text-slate-400">THIS IS NOT AN INVESTMENT RECOMMENDATION. Candidate values cover only the analyzed historical day and the INDICATIVE IEX DAM ENERGY COMPONENT.</p></header>
    <div className="flex flex-wrap items-end gap-3"><label className="text-xs">Forecast input cutoff<input aria-label="Sizing input date" className="mt-1 block rounded border border-slate-700 bg-slate-950 p-2" type="date" value={inputDate} onChange={event=>setInputDate(event.target.value)}/></label>
      <label className="text-xs">Capacity candidates (kWh)<input aria-label="Capacity candidates" className="mt-1 block w-72 rounded border border-slate-700 bg-slate-950 p-2" value={capacityInput} onChange={event=>setCapacityInput(event.target.value)}/></label>
      <label className="text-xs">Power candidates (kW)<input aria-label="Power candidates" className="mt-1 block w-56 rounded border border-slate-700 bg-slate-950 p-2" value={powerInput} onChange={event=>setPowerInput(event.target.value)}/></label>
      <button className="rounded bg-purple-700 px-4 py-2 text-sm font-semibold disabled:opacity-50" disabled={!inputDate||loading} onClick={run}>{loading?'Screening candidates…':'RUN HISTORICAL SIZING SCREEN'}</button></div>
    {error&&<div role="alert" className="rounded border border-rose-700 p-3 text-sm text-rose-300">Sizing unavailable: {error}</div>}
    {result&&<><div className="grid gap-3 md:grid-cols-4"><Metric title="Base throughput normalization" value={`${result.base_max_efc_per_day.toFixed(3)} EFC/day`}/><Metric title="Candidates" value={`${result.candidate_count}`}/><Metric title="Pareto efficient" value={`${result.pareto_efficient_count}`}/><Metric title="Uncertainty" value={result.uncertainty_result}/></div>
      <div className="rounded border border-slate-700 p-3"><h3 className="font-semibold">Net indicative benefit heatmap</h3><div className="mt-2 overflow-x-auto"><table className="w-full text-xs"><thead><tr><th className="p-2 text-left">Power / capacity</th>{displayedCapacities.map(capacity=><th key={capacity} className="p-2">{capacity} kWh</th>)}</tr></thead><tbody>{displayedPowers.map(power=><tr key={power}><th className="p-2 text-left">{power} kW</th>{displayedCapacities.map(capacity=>{const cell=cells.find(item=>item.capacity_kwh===capacity&&item.power_kw===power);return <td key={capacity} className="p-1"><button data-testid={`sizing-cell-${capacity}-${power}`} onClick={()=>cell&&setSelected(cell)} className="w-full rounded p-2" style={{backgroundColor:`rgba(126,34,206,${0.12+0.7*(cell?.intensity||0)})`}}>{cell?money(cell.net_indicative_benefit_inr):'—'}</button></td>;})}</tr>)}</tbody></table></div></div>
      <div className="grid gap-3 md:grid-cols-3"><Summary title="BEST ON ANALYZED HISTORICAL EVIDENCE" value={`${result.best_candidate.capacity_kwh} kWh / ${result.best_candidate.power_kw} kW · ${money(result.best_candidate.net_indicative_benefit_inr)}`}/><Summary title="COMPACT VALUE CANDIDATE" value={result.compact_value_candidate?`${result.compact_value_candidate.capacity_kwh} kWh / ${result.compact_value_candidate.power_kw} kW · ${money(result.compact_value_candidate.net_indicative_benefit_inr)} (at least 90% of maximum)`:'None'}/><Summary title="Evidence boundary" value={`Analyzed days: ${result.analyzed_days} · NOT LANDED ELECTRICITY COST`}/><Summary title="Highest value per kWh" value={`${result.best_per_kwh_candidate.capacity_kwh} kWh / ${result.best_per_kwh_candidate.power_kw} kW · ${money(result.best_per_kwh_candidate.net_indicative_benefit_inr)}`}/><Summary title="Highest value per kW" value={`${result.best_per_kw_candidate.capacity_kwh} kWh / ${result.best_per_kw_candidate.power_kw} kW · ${money(result.best_per_kw_candidate.net_indicative_benefit_inr)}`}/><Summary title="Candidate grid" value={`${displayedCapacities.join(', ')} kWh × ${displayedPowers.join(', ')} kW`}/></div>
      <div className="rounded border border-slate-700 p-3"><h3 className="font-semibold">Capacity vs net benefit by power</h3><div className="mt-2 grid gap-3 md:grid-cols-2">{displayedPowers.map(power=><div key={power}><strong className="text-xs">{power} kW</strong>{displayedCapacities.map(capacity=>{const item=sizingCandidate(result,capacity,power);const max=Math.max(...result.candidates.map(candidate=>candidate.net_indicative_benefit_inr),1);return <div key={capacity} className="mt-1 flex items-center gap-2 text-xs"><span className="w-20">{capacity} kWh</span><span className="h-3 rounded bg-purple-600" style={{width:`${Math.max(1,(item?.net_indicative_benefit_inr||0)/max*70)}%`}}/><span>{item?money(item.net_indicative_benefit_inr):'—'}</span></div>})}</div>)}</div></div>
      <div className="overflow-x-auto"><h3 className="font-semibold">Marginal value steps</h3><table className="w-full text-xs"><thead><tr><th>Dimension</th><th>Fixed value</th><th>Step</th><th>Incremental benefit</th><th>Benefit per added unit</th></tr></thead><tbody>{result.marginal_values.map((step,index)=><tr key={`${step.dimension}-${step.fixed_value}-${index}`} className="border-t border-slate-800"><td>{step.dimension}</td><td>{step.fixed_value}</td><td>{step.from_value} → {step.to_value}</td><td>{money(step.incremental_net_benefit_inr)}</td><td>{money(step.incremental_benefit_per_unit_inr)}</td></tr>)}</tbody></table></div>
      <div className="overflow-x-auto"><h3 className="font-semibold">Economic frontier and utilization</h3><table className="w-full text-xs"><thead><tr><th>Capacity</th><th>Power</th><th>Duration</th><th>Net benefit</th><th>Gross reduction</th><th>Degradation</th><th>EFC</th><th>Power / throughput / SOC use</th><th>Uncertainty</th><th>Pareto status</th></tr></thead><tbody>{result.candidates.map(candidate=><tr key={`${candidate.capacity_kwh}-${candidate.power_kw}`} className="border-t border-slate-800"><td><button className="p-2 text-left text-purple-300 underline" onClick={()=>setSelected(candidate)}>{candidate.capacity_kwh} kWh</button></td><td>{candidate.power_kw} kW</td><td>{candidate.duration_hours.toFixed(2)} h</td><td>{money(candidate.net_indicative_benefit_inr)}</td><td>{money(candidate.gross_iex_component_reduction_inr)}</td><td>{money(candidate.degradation_cost_inr)}</td><td>{candidate.equivalent_full_cycles.toFixed(3)}</td><td>{Math.max(candidate.charge_power_utilization_percent,candidate.discharge_power_utilization_percent).toFixed(1)}% / {candidate.throughput_utilization_percent.toFixed(1)}% / {candidate.usable_energy_utilization_percent.toFixed(1)}%</td><td>{candidate.uncertainty_status}</td><td>{candidate.pareto_status}</td></tr>)}</tbody></table></div>
      {selected&&<div data-testid="sizing-candidate-detail"><h3 className="mb-2 font-semibold">Candidate detail · {candidateName(selected)}</h3><BessSimulationPanel result={selected.dispatch} historical/></div>}</>}
  </section>;
}
function Metric({title,value}:{title:string;value:string}){return <div className="rounded border border-slate-700 p-3"><div className="text-xs text-slate-400">{title}</div><strong className="text-sm">{value}</strong></div>}
function Summary({title,value}:{title:string;value:string}){return <div className="rounded border border-purple-900 p-3"><strong className="text-xs text-purple-300">{title}</strong><div className="mt-1 text-sm">{value}</div></div>}
