'use client';
import { useEffect,useMemo,useRef,useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import { aggregateMultiDaySizing,runSequentialSizing,type CompletedSizingDay } from '@/lib/analytics/bess-multiday';
import type { BESSSizingResponseContract } from '@/types/analytics-contracts';

type EvidenceDay={date:string;eligible:boolean;forecast_ready:boolean;price_blocks:number;price_verification:string;reason_if_ineligible:string|null};
const capacities=[500,1000,1500,2000,3000,4000],powers=[250,500,750,1000];
const money=(value:number)=>`₹${value.toLocaleString(undefined,{maximumFractionDigits:2})}`;

export function MultiDayBessSizingPanel({siteId}:{siteId:string}){
  const supabase=useMemo(()=>createClient(),[]);const cancelled=useRef(false);
  const [days,setDays]=useState<EvidenceDay[]>([]),[selected,setSelected]=useState<string[]>([]),[loadingEvidence,setLoadingEvidence]=useState(true);
  const [from,setFrom]=useState(''),[to,setTo]=useState(''),[running,setRunning]=useState(false),[progress,setProgress]=useState({current_date:'',completed:0,failed:0});
  const [completed,setCompleted]=useState<CompletedSizingDay[]>([]),[failures,setFailures]=useState<Array<{date:string;error:string}>>([]),[error,setError]=useState<string|null>(null);
  const [totalElapsedMs,setTotalElapsedMs]=useState(0);
  useEffect(()=>{let active=true;void(async()=>{try{const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error('AUTHENTICATED_SESSION_REQUIRED');
    const response=await fetch(`/api/bess/sizing/evidence?site_id=${encodeURIComponent(siteId)}`,{headers:{Authorization:`Bearer ${session.access_token}`},cache:'no-store'});
    const body=await response.json();if(!response.ok)throw new Error(body.error||`HTTP ${response.status}`);if(active)setDays(body.days||[]);
  }catch(failure){if(active)setError(failure instanceof Error?failure.message:String(failure));}finally{if(active)setLoadingEvidence(false);}})();return()=>{active=false;cancelled.current=true;};},[siteId,supabase]);
  const eligible=days.filter(day=>day.eligible&&(!from||day.date>=from)&&(!to||day.date<=to));
  const aggregate=aggregateMultiDaySizing(completed);
  async function run(){if(!selected.length||selected.length>31)return;setRunning(true);setError(null);setCompleted([]);setFailures([]);cancelled.current=false;
    const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token){setError('AUTHENTICATED_SESSION_REQUIRED');setRunning(false);return;}
    const started=performance.now();const outcome=await runSequentialSizing(selected,async date=>{const response=await fetch('/api/bess/sizing',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({site_id:siteId,target_date:date,capacity_candidates_kwh:capacities,power_candidates_kw:powers})});
      const body=await response.json();if(!response.ok)throw new Error(body.error||`HTTP ${response.status}`);return body.result as BESSSizingResponseContract;},()=>cancelled.current,state=>setProgress(state));
    setCompleted(outcome.completed.map(item=>({date:item.date,result:item.value,request_runtime_ms:item.runtime_ms})));
    setFailures(outcome.failures);setProgress(state=>({...state,completed:outcome.completed.length,failed:outcome.failures.length}));
    setTotalElapsedMs(performance.now()-started);if(outcome.cancelled)setError('ANALYSIS_CANCELLED_COMPLETED_RESULTS_RETAINED');setRunning(false);
  }
  return <div className="space-y-4" data-testid="multi-day-bess-sizing"><header><h2 className="font-bold text-purple-200">MULTI-DAY BESS SIZING SCREEN</h2>
    <div className="text-xs font-semibold text-amber-200">NOT AN INVESTMENT RECOMMENDATION · NOT ANNUALIZED · NOT LANDED ELECTRICITY COST · NOT SUFFICIENT FOR INVESTMENT DECISION</div></header>
    {loadingEvidence&&<div>Loading verified historical evidence…</div>}{error&&<div role="alert" className="rounded border border-amber-700 p-2 text-sm text-amber-200">{error}</div>}
    <section className="rounded border border-slate-700 p-3"><strong>AVAILABLE VERIFIED HISTORICAL DAYS</strong><div className="mt-2 flex flex-wrap gap-2"><label className="text-xs">From<input aria-label="Multi-day from" type="date" value={from} onChange={event=>setFrom(event.target.value)} className="ml-2 bg-slate-950"/></label><label className="text-xs">To<input aria-label="Multi-day to" type="date" value={to} onChange={event=>setTo(event.target.value)} className="ml-2 bg-slate-950"/></label>
      <button onClick={()=>setSelected(eligible.slice(0,31).map(day=>day.date))} className="rounded border px-2 text-xs">Select all eligible (max 31)</button></div>
      <div className="mt-2 grid max-h-52 gap-1 overflow-auto md:grid-cols-3">{days.filter(day=>(!from||day.date>=from)&&(!to||day.date<=to)).map(day=><label key={day.date} className={`rounded border p-2 text-xs ${day.eligible?'border-slate-700':'border-rose-900 text-slate-500'}`} title={day.reason_if_ineligible||'Eligible'}><input type="checkbox" disabled={!day.eligible||running} checked={selected.includes(day.date)} onChange={event=>setSelected(value=>event.target.checked?[...value,day.date]:value.filter(date=>date!==day.date))}/> {day.date} · {day.price_blocks}/96 · {day.price_verification}{!day.eligible&&` · ${day.reason_if_ineligible}`}</label>)}</div></section>
    <div className="flex gap-2"><button disabled={running||selected.length===0||selected.length>31} onClick={run} className="rounded bg-purple-700 px-4 py-2 text-sm disabled:opacity-50">RUN MULTI-DAY SCREEN</button>{running&&<button onClick={()=>{cancelled.current=true}} className="rounded border border-rose-600 px-4 py-2 text-sm">CANCEL ANALYSIS</button>}</div>
    {(running||completed.length>0||failures.length>0)&&<div data-testid="multi-day-progress" className="rounded border border-slate-700 p-3 text-sm">Analyzing {Math.min(progress.completed+progress.failed+1,selected.length)} of {selected.length}<div>Current date: {progress.current_date||'—'}</div><div>Completed: {progress.completed} · Failed: {progress.failed}</div></div>}
    {failures.length>0&&<div className="rounded border border-rose-800 p-3 text-sm"><strong>Failed dates</strong>{failures.map(item=><div key={item.date}>{item.date}: {item.error}</div>)}</div>}
    {aggregate&&<><div className="grid gap-3 md:grid-cols-4"><Card title="Analyzed days" value={`${aggregate.analyzed_days}`}/><Card title="Date range" value={`${aggregate.first_date} – ${aggregate.last_date}`}/><Card title="Months represented" value={`${aggregate.months.join(', ')} (${aggregate.unique_months})`}/><Card title="Evidence status" value={aggregate.evidence_status}/><Card title="Highest median net benefit" value={`${aggregate.best_candidate.capacity_kwh} kWh / ${aggregate.best_candidate.power_kw} kW`}/><Card title="Median daily indicative benefit" value={money(aggregate.best_candidate.median_daily_net_benefit)}/><Card title="Positive / no-action days" value={`${aggregate.best_candidate.positive_day_percent.toFixed(1)}% / ${aggregate.best_candidate.no_action_day_percent.toFixed(1)}%`}/><Card title="Leader / uncertainty" value={`${aggregate.leader_stability} · ${aggregate.best_candidate.uncertainty_robust_day_percent.toFixed(1)}% robust`}/></div>
      <section className="overflow-x-auto rounded border border-slate-700 p-3"><h3 className="font-semibold">Aggregate sizing heatmap · median daily net benefit</h3><table className="w-full text-xs"><thead><tr><th>Power / capacity</th>{capacities.map(capacity=><th key={capacity}>{capacity} kWh</th>)}</tr></thead><tbody>{powers.map(power=><tr key={power}><th>{power} kW</th>{capacities.map(capacity=>{const item=aggregate.candidates.find(candidate=>candidate.capacity_kwh===capacity&&candidate.power_kw===power);return <td key={capacity} className="p-2 text-center">{item?money(item.median_daily_net_benefit):'—'}</td>})}</tr>)}</tbody></table></section>
      <section className="rounded border border-slate-700 p-3"><h3 className="font-semibold">Daily best-candidate timeline</h3><div className="flex flex-wrap gap-2">{aggregate.daily_leaders.map(item=><span key={item.date} className="rounded bg-slate-800 p-2 text-xs">{item.date} · {item.candidate.replace(':',' kWh / ')} kW</span>)}</div></section>
      <section className="overflow-x-auto rounded border border-slate-700 p-3"><h3 className="font-semibold">Marginal capacity and power value</h3><table className="w-full text-xs"><thead><tr><th>Dimension</th><th>Fixed</th><th>Step</th><th>Δ median benefit</th><th>Per added unit</th></tr></thead><tbody>{aggregate.marginal_values.map((item,index)=><tr key={index}><td>{item.dimension}</td><td>{item.fixed_value}</td><td>{item.from_value} → {item.to_value}</td><td>{money(item.delta_median_benefit)}</td><td>{money(item.benefit_per_added_unit)}</td></tr>)}</tbody></table></section>
      <section className="overflow-x-auto"><h3 className="font-semibold">Full candidate evidence</h3><table className="w-full text-xs"><thead><tr><th>Capacity</th><th>Power</th><th>Duration</th><th>Days</th><th>Median / mean</th><th>P10 / P90</th><th>Positive</th><th>No action</th><th>Median EFC</th><th>Median throughput</th><th>Robust</th><th>Pareto</th><th>Leader days</th></tr></thead><tbody>{aggregate.candidates.map(item=><tr key={`${item.capacity_kwh}-${item.power_kw}`} className="border-t border-slate-800"><td>{item.capacity_kwh}</td><td>{item.power_kw}</td><td>{item.duration_hours.toFixed(2)}</td><td>{item.analyzed_days}</td><td>{money(item.median_daily_net_benefit)} / {money(item.mean_daily_net_benefit)}</td><td>{money(item.p10_daily_net_benefit)} / {money(item.p90_daily_net_benefit)}</td><td>{item.positive_day_percent.toFixed(1)}%</td><td>{item.no_action_day_percent.toFixed(1)}%</td><td>{item.median_efc.toFixed(3)}</td><td>{item.median_throughput_kwh.toFixed(1)} kWh</td><td>{item.uncertainty_robust_day_percent.toFixed(1)}%</td><td>{item.pareto_status}</td><td>{item.leader_days}</td></tr>)}</tbody></table></section>
      <section className="rounded border border-slate-700 p-3"><h3 className="font-semibold">Pareto candidate daily benefit distribution</h3>{aggregate.candidates.filter(item=>item.pareto_status==='MULTI_DAY_PARETO_EFFICIENT').map(item=><div key={`${item.capacity_kwh}-${item.power_kw}`} className="mt-1 text-xs">{item.capacity_kwh} kWh / {item.power_kw} kW · min {money(item.minimum_daily_net_benefit)} · P10 {money(item.p10_daily_net_benefit)} · median {money(item.median_daily_net_benefit)} · P90 {money(item.p90_daily_net_benefit)} · max {money(item.maximum_daily_net_benefit)}</div>)}</section>
      <div className="text-xs text-slate-400">Median request {aggregate.median_request_runtime_ms.toFixed(0)} ms · slowest {aggregate.slowest_request_runtime_ms.toFixed(0)} ms · completed-request time {aggregate.total_client_runtime_ms.toFixed(0)} ms · total end-to-end client analysis {totalElapsedMs.toFixed(0)} ms</div></>}
  </div>;
}
function Card({title,value}:{title:string;value:string}){return <div className="rounded border border-slate-700 p-3"><div className="text-xs text-slate-400">{title}</div><strong className="text-sm">{value}</strong></div>}
