BEGIN;

CREATE TABLE public.market_price_imports (
  id uuid PRIMARY KEY DEFAULT extensions.uuid_generate_v4(),
  exchange text NOT NULL CHECK (exchange = 'IEX'),
  market_product text NOT NULL CHECK (market_product = 'DAM'),
  source_type text NOT NULL CHECK (source_type = 'OFFICIAL_EXCHANGE_EXPORT'),
  source_reference text NOT NULL CHECK (length(btrim(source_reference)) > 0),
  source_file_name text NOT NULL CHECK (length(btrim(source_file_name)) > 0),
  source_file_hash char(64) NOT NULL UNIQUE CHECK (source_file_hash ~ '^[0-9a-f]{64}$'),
  published_at timestamptz,
  fetched_at timestamptz NOT NULL,
  ingested_at timestamptz NOT NULL DEFAULT now(),
  imported_by uuid NOT NULL REFERENCES public.user_profiles(id),
  provenance_status text NOT NULL CHECK (provenance_status = 'OFFICIAL_SOURCE_CONFIRMED'),
  verification_status text NOT NULL CHECK (verification_status = 'VERIFIED'),
  delivery_date_start date NOT NULL,
  delivery_date_end date NOT NULL,
  total_rows integer NOT NULL CHECK (total_rows > 0),
  total_days integer NOT NULL CHECK (total_days > 0),
  CHECK (delivery_date_end >= delivery_date_start)
);

CREATE TABLE public.market_price_blocks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  import_id uuid NOT NULL REFERENCES public.market_price_imports(id) ON DELETE RESTRICT,
  exchange text NOT NULL CHECK (exchange = 'IEX'),
  market_product text NOT NULL CHECK (market_product = 'DAM'),
  delivery_date date NOT NULL,
  block_index smallint NOT NULL CHECK (block_index BETWEEN 1 AND 96),
  time_start varchar(5) NOT NULL CHECK (time_start ~ '^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$'),
  time_end varchar(5) NOT NULL CHECK (time_end = '24:00' OR time_end ~ '^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$'),
  mcp_rs_per_mwh numeric(14,4) NOT NULL CHECK (mcp_rs_per_mwh >= 0),
  source_type text NOT NULL CHECK (source_type = 'OFFICIAL_EXCHANGE_EXPORT'),
  source_reference text NOT NULL,
  source_file_hash char(64) NOT NULL CHECK (source_file_hash ~ '^[0-9a-f]{64}$'),
  published_at timestamptz,
  fetched_at timestamptz NOT NULL,
  ingested_at timestamptz NOT NULL DEFAULT now(),
  provenance_status text NOT NULL CHECK (provenance_status = 'OFFICIAL_SOURCE_CONFIRMED'),
  verification_status text NOT NULL CHECK (verification_status = 'VERIFIED'),
  UNIQUE (exchange, market_product, delivery_date, block_index)
);

CREATE INDEX idx_market_price_blocks_delivery
  ON public.market_price_blocks(exchange, market_product, delivery_date DESC, block_index);
CREATE INDEX idx_market_price_blocks_import ON public.market_price_blocks(import_id);

ALTER TABLE public.market_price_imports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.market_price_blocks ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.market_price_imports, public.market_price_blocks FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON SEQUENCE public.market_price_blocks_id_seq FROM PUBLIC, anon, authenticated, service_role;
GRANT SELECT ON public.market_price_imports, public.market_price_blocks TO service_role;

CREATE FUNCTION public.commit_iex_dam_market_prices(
  p_actor_id uuid,
  p_source_file_name text,
  p_source_file_hash text,
  p_source_reference text,
  p_published_at timestamptz,
  p_fetched_at timestamptz,
  p_rows jsonb
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp AS $$
DECLARE
  v_import_id uuid;
  v_total_rows integer;
  v_total_days integer;
  v_min_date date;
  v_max_date date;
  v_role text;
BEGIN
  PERFORM public.assert_backend_caller();
  IF p_actor_id IS NULL OR NOT EXISTS (
    SELECT 1 FROM public.user_profiles up
    WHERE up.id = p_actor_id AND up.is_platform_admin
  ) THEN
    SELECT m.role INTO v_role FROM public.memberships m
    WHERE m.user_id = p_actor_id AND m.is_active AND m.role = 'AETHEON_ANALYST'
      AND m.expires_at IS NOT NULL AND m.expires_at > now()
    LIMIT 1;
    IF v_role IS NULL THEN
      RAISE EXCEPTION 'PLATFORM_MARKET_DATA_ADMIN_REQUIRED' USING ERRCODE = '42501';
    END IF;
  END IF;
  IF p_source_file_name IS NULL OR length(btrim(p_source_file_name)) = 0 OR
     p_source_reference IS NULL OR p_source_reference !~* '^https://([^/]+\.)?(iexindia\.com|iexindia\.in)(/|$)' OR
     p_source_file_hash !~ '^[0-9a-f]{64}$' OR p_fetched_at IS NULL THEN
    RAISE EXCEPTION 'INVALID_OFFICIAL_SOURCE_PROVENANCE' USING ERRCODE = '22023';
  END IF;
  IF jsonb_typeof(p_rows) <> 'array' OR jsonb_array_length(p_rows) = 0 THEN
    RAISE EXCEPTION 'EMPTY_MARKET_PRICE_IMPORT' USING ERRCODE = '22023';
  END IF;

  WITH rows AS (
    SELECT * FROM jsonb_to_recordset(p_rows) AS x(
      delivery_date date, block_index integer, time_start text, time_end text, mcp_rs_per_mwh numeric
    )
  ), invalid AS (
    SELECT 1 FROM rows WHERE delivery_date IS NULL OR block_index NOT BETWEEN 1 AND 96
      OR mcp_rs_per_mwh IS NULL OR mcp_rs_per_mwh < 0
      OR time_start IS DISTINCT FROM to_char(time '00:00' + ((block_index - 1) * interval '15 minutes'), 'HH24:MI')
      OR time_end IS DISTINCT FROM CASE WHEN block_index = 96 THEN '24:00'
           ELSE to_char(time '00:00' + (block_index * interval '15 minutes'), 'HH24:MI') END
  ), bad_days AS (
    SELECT delivery_date FROM rows GROUP BY delivery_date
    HAVING count(*) <> 96 OR count(DISTINCT block_index) <> 96 OR min(block_index) <> 1 OR max(block_index) <> 96
  )
  SELECT count(*), count(DISTINCT delivery_date), min(delivery_date), max(delivery_date)
    INTO v_total_rows, v_total_days, v_min_date, v_max_date FROM rows;
  IF EXISTS (
    WITH rows AS (SELECT * FROM jsonb_to_recordset(p_rows) AS x(delivery_date date, block_index integer, time_start text, time_end text, mcp_rs_per_mwh numeric))
    SELECT 1 FROM rows WHERE delivery_date IS NULL OR block_index NOT BETWEEN 1 AND 96 OR mcp_rs_per_mwh IS NULL OR mcp_rs_per_mwh < 0
      OR time_start IS DISTINCT FROM to_char(time '00:00' + ((block_index - 1) * interval '15 minutes'), 'HH24:MI')
      OR time_end IS DISTINCT FROM CASE WHEN block_index = 96 THEN '24:00' ELSE to_char(time '00:00' + (block_index * interval '15 minutes'), 'HH24:MI') END
  ) OR EXISTS (
    WITH rows AS (SELECT * FROM jsonb_to_recordset(p_rows) AS x(delivery_date date, block_index integer, time_start text, time_end text, mcp_rs_per_mwh numeric))
    SELECT 1 FROM rows GROUP BY delivery_date HAVING count(*) <> 96 OR count(DISTINCT block_index) <> 96 OR min(block_index) <> 1 OR max(block_index) <> 96
  ) THEN
    RAISE EXCEPTION 'INVALID_96_BLOCK_MARKET_DAY' USING ERRCODE = '22023';
  END IF;

  INSERT INTO public.market_price_imports(exchange, market_product, source_type, source_reference,
    source_file_name, source_file_hash, published_at, fetched_at, imported_by, provenance_status,
    verification_status, delivery_date_start, delivery_date_end, total_rows, total_days)
  VALUES ('IEX','DAM','OFFICIAL_EXCHANGE_EXPORT',btrim(p_source_reference),btrim(p_source_file_name),
    p_source_file_hash,p_published_at,p_fetched_at,p_actor_id,'OFFICIAL_SOURCE_CONFIRMED','VERIFIED',
    v_min_date,v_max_date,v_total_rows,v_total_days)
  RETURNING id INTO v_import_id;

  INSERT INTO public.market_price_blocks(import_id,exchange,market_product,delivery_date,block_index,time_start,time_end,
    mcp_rs_per_mwh,source_type,source_reference,source_file_hash,published_at,fetched_at,provenance_status,verification_status)
  SELECT v_import_id,'IEX','DAM',r.delivery_date,r.block_index,r.time_start,r.time_end,r.mcp_rs_per_mwh,
    'OFFICIAL_EXCHANGE_EXPORT',btrim(p_source_reference),p_source_file_hash,p_published_at,p_fetched_at,
    'OFFICIAL_SOURCE_CONFIRMED','VERIFIED'
  FROM jsonb_to_recordset(p_rows) AS r(delivery_date date, block_index integer, time_start text, time_end text, mcp_rs_per_mwh numeric);

  INSERT INTO public.audit_logs(actor_id,actor_role,action,entity_type,entity_id,details)
  VALUES (p_actor_id,COALESCE(v_role,'PLATFORM_ADMIN'),'IEX_DAM_PRICE_IMPORT','MARKET_PRICE_IMPORT',v_import_id::text,
    jsonb_build_object('exchange','IEX','market_product','DAM','source_file_hash',p_source_file_hash,
      'delivery_date_start',v_min_date,'delivery_date_end',v_max_date,'total_rows',v_total_rows,'total_days',v_total_days));
  RETURN jsonb_build_object('import_id',v_import_id,'status','COMMITTED','total_rows',v_total_rows,'total_days',v_total_days,
    'delivery_date_start',v_min_date,'delivery_date_end',v_max_date);
EXCEPTION WHEN unique_violation THEN
  IF EXISTS (SELECT 1 FROM public.market_price_imports WHERE source_file_hash=p_source_file_hash) THEN
    RAISE EXCEPTION 'DUPLICATE_MARKET_PRICE_FILE' USING ERRCODE = '23505';
  END IF;
  RAISE EXCEPTION 'MARKET_PRICE_DATE_ALREADY_IMPORTED' USING ERRCODE = '23505';
END $$;

REVOKE ALL ON FUNCTION public.commit_iex_dam_market_prices(uuid,text,text,text,timestamptz,timestamptz,jsonb)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.commit_iex_dam_market_prices(uuid,text,text,text,timestamptz,timestamptz,jsonb)
  TO service_role;

NOTIFY pgrst, 'reload schema';
COMMIT;
