import {beforeEach,describe,expect,it,vi} from 'vitest';
import {NextRequest,NextResponse} from 'next/server';
vi.mock('server-only',()=>({}));
const mocks=vi.hoisted(()=>({authorize:vi.fn(),history:vi.fn(),profile:vi.fn(),prices:vi.fn(),catalog:vi.fn(),readiness:vi.fn()}));
vi.mock('@/lib/auth/api-guard',()=>({authorizeApiRequest:mocks.authorize}));
vi.mock('@/lib/analytics/grid-input-evidence',()=>({loadGridHistoricalInput:mocks.history}));
vi.mock('@/lib/analytics/bess-simulation',()=>({loadBessProfile:mocks.profile}));
vi.mock('@/lib/analytics/bess-sizing-evidence',()=>({loadBessSizingPriceEvidence:mocks.prices,buildBessSizingEvidenceCatalog:mocks.catalog,evaluateHistoricalBessSizingReadiness:mocks.readiness}));
vi.mock('@/lib/supabase/admin',()=>({createAdminClient:()=>({})}));
vi.mock('@/lib/analytics/domain-safety',()=>({operatingToday:()=> '2026-09-16',validDate:(value:unknown)=>typeof value==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(value)}));
import {GET} from '@/app/api/bess/sizing/evidence/route';
const siteId='site-1',client={} as any;const request=(token='token')=>new NextRequest(`http://localhost/api/bess/sizing/evidence?site_id=${siteId}`,{headers:token?{Authorization:`Bearer ${token}`}:{}});
describe('BESS sizing evidence endpoint',()=>{beforeEach(()=>{vi.clearAllMocks();mocks.authorize.mockResolvedValue({authorized:true,organisationId:'org',isDemo:false,authenticatedClient:client,site:{id:siteId,organisation_id:'org'}});mocks.history.mockResolvedValue({complete_days:[]});mocks.profile.mockResolvedValue({});mocks.prices.mockResolvedValue([]);mocks.catalog.mockReturnValue([]);});
  it('authenticates, authorizes BESS entitlement and returns sanitized catalog',async()=>{const response=await GET(request());expect(response.status).toBe(200);expect(mocks.authorize).toHaveBeenCalledWith(expect.anything(),{siteId,productId:'BESS_ARBITRAGE',requireBearer:true});expect(mocks.catalog).toHaveBeenCalled();});
  it('returns only canonically READY dates in the collection consumed by the UI',async()=>{const dates=['2025-07-02','2025-07-06','2025-09-03','2025-09-07','2025-11-05','2025-11-09','2026-01-07','2026-01-11','2026-03-04','2026-03-08','2026-04-12','2026-05-01'];
    const failed=new Set(['2025-11-05','2025-11-09','2026-01-11','2026-03-08']);mocks.catalog.mockReturnValue(dates.map(date=>({date,sizing_ready:false,readiness_status:'FORECAST_READINESS_NOT_EVALUATED'})));
    mocks.readiness.mockImplementation(async({targetDate}:{targetDate:string})=>({date:targetDate,eligible:!failed.has(targetDate),sizing_ready:!failed.has(targetDate),
      readiness_status:failed.has(targetDate)?'FORECAST_UNAVAILABLE':'READY',reason_if_ineligible:failed.has(targetDate)?'FORECAST_UNAVAILABLE':null,profile:{},forecast:{},prices:[]}));
    const response=await GET(request());const payload=await response.json();expect(payload.diagnostic_days).toHaveLength(12);expect(payload.days).toHaveLength(8);
    expect(payload.eligible_dates).toHaveLength(8);expect(payload.eligible_dates).not.toEqual(expect.arrayContaining([...failed]));expect(mocks.readiness).toHaveBeenCalledTimes(12);});
  it('uses canonical compute readiness for a requested discovery date and strips compute artifacts',async()=>{mocks.readiness.mockResolvedValue({date:'2026-05-01',sizing_ready:false,eligible:false,reason_if_ineligible:'FORECAST_UNAVAILABLE',profile:{secret:true},forecast:{blocks:[]},prices:[{secret:true}]});
    const response=await GET(new NextRequest(`http://localhost/api/bess/sizing/evidence?site_id=${siteId}&target_date=2026-05-01`,{headers:{Authorization:'Bearer token'}}));
    expect(response.status).toBe(200);expect(mocks.readiness).toHaveBeenCalledWith(expect.objectContaining({client,siteId,organisationId:'org',targetDate:'2026-05-01'}));
    const payload=await response.json();expect(payload.day).toMatchObject({date:'2026-05-01',sizing_ready:false,reason_if_ineligible:'FORECAST_UNAVAILABLE'});
    expect(payload.day).not.toHaveProperty('profile');expect(payload.day).not.toHaveProperty('forecast');expect(payload.day).not.toHaveProperty('prices');});
  it('denies cross-tenant access before any evidence load',async()=>{mocks.authorize.mockResolvedValue({authorized:false,response:NextResponse.json({error:'SITE_ACCESS_DENIED'},{status:403})});expect((await GET(request())).status).toBe(403);expect(mocks.history).not.toHaveBeenCalled();expect(mocks.prices).not.toHaveBeenCalled();});
  it('requires bearer authentication',async()=>{expect((await GET(request(''))).status).toBe(401);expect(mocks.authorize).not.toHaveBeenCalled();});});
